W0615 19:55:18.290000 1934378 site-packages/torch/distributed/run.py:766] 
W0615 19:55:18.290000 1934378 site-packages/torch/distributed/run.py:766] *****************************************
W0615 19:55:18.290000 1934378 site-packages/torch/distributed/run.py:766] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0615 19:55:18.290000 1934378 site-packages/torch/distributed/run.py:766] *****************************************
W0615 19:55:18.307000 2059372 site-packages/torch/distributed/run.py:766] 
W0615 19:55:18.307000 2059372 site-packages/torch/distributed/run.py:766] *****************************************
W0615 19:55:18.307000 2059372 site-packages/torch/distributed/run.py:766] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0615 19:55:18.307000 2059372 site-packages/torch/distributed/run.py:766] *****************************************
W0615 19:55:18.314000 875742 site-packages/torch/distributed/run.py:766] 
W0615 19:55:18.314000 875742 site-packages/torch/distributed/run.py:766] *****************************************
W0615 19:55:18.314000 875742 site-packages/torch/distributed/run.py:766] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0615 19:55:18.314000 875742 site-packages/torch/distributed/run.py:766] *****************************************
W0615 19:55:18.315000 997611 site-packages/torch/distributed/run.py:766] 
W0615 19:55:18.315000 997611 site-packages/torch/distributed/run.py:766] *****************************************
W0615 19:55:18.315000 997611 site-packages/torch/distributed/run.py:766] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0615 19:55:18.315000 997611 site-packages/torch/distributed/run.py:766] *****************************************
W0615 19:55:18.290000 1934379 site-packages/torch/distributed/run.py:766] 
W0615 19:55:18.290000 1934379 site-packages/torch/distributed/run.py:766] *****************************************
W0615 19:55:18.290000 1934379 site-packages/torch/distributed/run.py:766] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0615 19:55:18.290000 1934379 site-packages/torch/distributed/run.py:766] *****************************************
W0615 19:55:18.290000 1934380 site-packages/torch/distributed/run.py:766] 
W0615 19:55:18.290000 1934380 site-packages/torch/distributed/run.py:766] *****************************************
W0615 19:55:18.290000 1934380 site-packages/torch/distributed/run.py:766] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0615 19:55:18.290000 1934380 site-packages/torch/distributed/run.py:766] *****************************************
W0615 19:55:18.290000 1934381 site-packages/torch/distributed/run.py:766] 
W0615 19:55:18.290000 1934381 site-packages/torch/distributed/run.py:766] *****************************************
W0615 19:55:18.290000 1934381 site-packages/torch/distributed/run.py:766] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0615 19:55:18.290000 1934381 site-packages/torch/distributed/run.py:766] *****************************************
W0615 19:55:18.307000 2059375 site-packages/torch/distributed/run.py:766] 
W0615 19:55:18.307000 2059375 site-packages/torch/distributed/run.py:766] *****************************************
W0615 19:55:18.307000 2059375 site-packages/torch/distributed/run.py:766] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0615 19:55:18.307000 2059375 site-packages/torch/distributed/run.py:766] *****************************************
W0615 19:55:18.307000 2059374 site-packages/torch/distributed/run.py:766] 
W0615 19:55:18.307000 2059374 site-packages/torch/distributed/run.py:766] *****************************************
W0615 19:55:18.307000 2059374 site-packages/torch/distributed/run.py:766] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0615 19:55:18.307000 2059374 site-packages/torch/distributed/run.py:766] *****************************************
W0615 19:55:18.307000 2059373 site-packages/torch/distributed/run.py:766] 
W0615 19:55:18.307000 2059373 site-packages/torch/distributed/run.py:766] *****************************************
W0615 19:55:18.307000 2059373 site-packages/torch/distributed/run.py:766] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0615 19:55:18.307000 2059373 site-packages/torch/distributed/run.py:766] *****************************************
W0615 19:55:18.314000 875743 site-packages/torch/distributed/run.py:766] 
W0615 19:55:18.314000 875743 site-packages/torch/distributed/run.py:766] *****************************************
W0615 19:55:18.314000 875743 site-packages/torch/distributed/run.py:766] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0615 19:55:18.314000 875743 site-packages/torch/distributed/run.py:766] *****************************************
W0615 19:55:18.314000 875741 site-packages/torch/distributed/run.py:766] 
W0615 19:55:18.314000 875741 site-packages/torch/distributed/run.py:766] *****************************************
W0615 19:55:18.314000 875741 site-packages/torch/distributed/run.py:766] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0615 19:55:18.314000 875741 site-packages/torch/distributed/run.py:766] *****************************************
W0615 19:55:18.314000 875744 site-packages/torch/distributed/run.py:766] 
W0615 19:55:18.314000 875744 site-packages/torch/distributed/run.py:766] *****************************************
W0615 19:55:18.314000 875744 site-packages/torch/distributed/run.py:766] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0615 19:55:18.314000 875744 site-packages/torch/distributed/run.py:766] *****************************************
W0615 19:55:18.315000 997608 site-packages/torch/distributed/run.py:766] 
W0615 19:55:18.315000 997608 site-packages/torch/distributed/run.py:766] *****************************************
W0615 19:55:18.315000 997608 site-packages/torch/distributed/run.py:766] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0615 19:55:18.315000 997608 site-packages/torch/distributed/run.py:766] *****************************************
W0615 19:55:18.315000 997609 site-packages/torch/distributed/run.py:766] 
W0615 19:55:18.315000 997609 site-packages/torch/distributed/run.py:766] *****************************************
W0615 19:55:18.315000 997609 site-packages/torch/distributed/run.py:766] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0615 19:55:18.315000 997609 site-packages/torch/distributed/run.py:766] *****************************************
W0615 19:55:18.315000 997610 site-packages/torch/distributed/run.py:766] 
W0615 19:55:18.315000 997610 site-packages/torch/distributed/run.py:766] *****************************************
W0615 19:55:18.315000 997610 site-packages/torch/distributed/run.py:766] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0615 19:55:18.315000 997610 site-packages/torch/distributed/run.py:766] *****************************************
Traceback (most recent call last):
Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 169, in <module>
Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 169, in <module>
  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 169, in <module>
Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 169, in <module>
    main_train(
  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 87, in main_train
    main_train(
  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 87, in main_train
    main_train(
  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 87, in main_train
    main_train(    print(f"[RANK {rank}] Hi! My local rank is {local_rank}, global rank is {rank}, world size is {world_size}")
    print(f"[RANK {rank}] Hi! My local rank is {local_rank}, global rank is {rank}, world size is {world_size}")
UnboundLocalError: local variable 'rank' referenced before assignmentUnboundLocalError
: local variable 'rank' referenced before assignment

  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 87, in main_train
    print(f"[RANK {rank}] Hi! My local rank is {local_rank}, global rank is {rank}, world size is {world_size}")
UnboundLocalError: local variable 'rank' referenced before assignment
    print(f"[RANK {rank}] Hi! My local rank is {local_rank}, global rank is {rank}, world size is {world_size}")
UnboundLocalError: local variable 'rank' referenced before assignment
Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 169, in <module>
Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 169, in <module>
    main_train(
  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 87, in main_train
    main_train(
  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 87, in main_train
Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 169, in <module>
Traceback (most recent call last):
    print(f"[RANK {rank}] Hi! My local rank is {local_rank}, global rank is {rank}, world size is {world_size}")
  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 169, in <module>
UnboundLocalError: local variable 'rank' referenced before assignment
    print(f"[RANK {rank}] Hi! My local rank is {local_rank}, global rank is {rank}, world size is {world_size}")
UnboundLocalError: local variable 'rank' referenced before assignment
    main_train(
  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 87, in main_train
    main_train(
  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 87, in main_train
    print(f"[RANK {rank}] Hi! My local rank is {local_rank}, global rank is {rank}, world size is {world_size}")
UnboundLocalError: local variable 'rank' referenced before assignment
    print(f"[RANK {rank}] Hi! My local rank is {local_rank}, global rank is {rank}, world size is {world_size}")
UnboundLocalError: local variable 'rank' referenced before assignment
E0615 19:55:24.184000 2059372 site-packages/torch/distributed/elastic/multiprocessing/api.py:874] failed (exitcode: 1) local_rank: 0 (pid: 2059401) of binary: /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python
E0615 19:55:24.185000 875741 site-packages/torch/distributed/elastic/multiprocessing/api.py:874] failed (exitcode: 1) local_rank: 0 (pid: 876001) of binary: /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python
Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/torchrun", line 10, in <module>
Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/torchrun", line 10, in <module>
    sys.exit(main())
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
    sys.exit(main())
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in main
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in main
    run(args)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 883, in run
    run(args)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 883, in run
    elastic_launch(
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 270, in launch_agent
    elastic_launch(
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-06-15_19:55:24
  host      : lrdn1582.leonardo.local
  rank      : 9 (local_rank: 1)
  exitcode  : 1 (pid: 2059402)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2025-06-15_19:55:24
  host      : lrdn1582.leonardo.local
  rank      : 10 (local_rank: 2)
  exitcode  : 1 (pid: 2059403)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2025-06-15_19:55:24
  host      : lrdn1582-net5-3.leonardo.local
  rank      : 11 (local_rank: 3)
  exitcode  : 1 (pid: 2059404)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 270, in launch_agent
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-06-15_19:55:24
  host      : lrdn1582-net5-3.leonardo.local
  rank      : 8 (local_rank: 0)
  exitcode  : 1 (pid: 2059401)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-06-15_19:55:24
  host      : lrdn1590.leonardo.local
  rank      : 13 (local_rank: 1)
  exitcode  : 1 (pid: 876002)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2025-06-15_19:55:24
  host      : lrdn1590-net5-3.leonardo.local
  rank      : 14 (local_rank: 2)
  exitcode  : 1 (pid: 876003)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2025-06-15_19:55:24
  host      : lrdn1590-net5-3.leonardo.local
  rank      : 15 (local_rank: 3)
  exitcode  : 1 (pid: 876004)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-06-15_19:55:24
  host      : lrdn1590-net5-3.leonardo.local
  rank      : 12 (local_rank: 0)
  exitcode  : 1 (pid: 876001)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/torchrun", line 10, in <module>
    sys.exit(main())
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in main
    run(args)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 883, in run
    elastic_launch(
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 265, in launch_agent
    if result.is_failed():
AttributeError: 'NoneType' object has no attribute 'is_failed'
srun: error: lrdn1590: task 12: Exited with exit code 1
srun: error: lrdn1582: task 8: Exited with exit code 1
Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/torchrun", line 10, in <module>
    sys.exit(main())
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in main
    run(args)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 883, in run
    elastic_launch(
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 265, in launch_agent
    if result.is_failed():
AttributeError: 'NoneType' object has no attribute 'is_failed'
Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/torchrun", line 10, in <module>
    sys.exit(main())
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in main
    run(args)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 883, in run
    elastic_launch(
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 265, in launch_agent
    if result.is_failed():
AttributeError: 'NoneType' object has no attribute 'is_failed'
Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/torchrun", line 10, in <module>
    sys.exit(main())
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in main
    run(args)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 883, in run
    elastic_launch(
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 265, in launch_agent
    if result.is_failed():
AttributeError: 'NoneType' object has no attribute 'is_failed'
Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/torchrun", line 10, in <module>
    sys.exit(main())
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in main
    run(args)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 883, in run
    elastic_launch(
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 265, in launch_agent
    if result.is_failed():
AttributeError: 'NoneType' object has no attribute 'is_failed'
Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/torchrun", line 10, in <module>
    sys.exit(main())
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in main
    run(args)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 883, in run
    elastic_launch(
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 265, in launch_agent
    if result.is_failed():
AttributeError: 'NoneType' object has no attribute 'is_failed'
Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/torchrun", line 10, in <module>
    sys.exit(main())
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in main
    run(args)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 883, in run
    elastic_launch(
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 265, in launch_agent
    if result.is_failed():
AttributeError: 'NoneType' object has no attribute 'is_failed'
Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/torchrun", line 10, in <module>
    sys.exit(main())
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in main
    run(args)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 883, in run
    elastic_launch(
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 265, in launch_agent
    if result.is_failed():
AttributeError: 'NoneType' object has no attribute 'is_failed'
Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/torchrun", line 10, in <module>
    sys.exit(main())
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in main
    run(args)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 883, in run
    elastic_launch(
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 265, in launch_agent
    if result.is_failed():
AttributeError: 'NoneType' object has no attribute 'is_failed'
Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/torchrun", line 10, in <module>
    sys.exit(main())
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in main
    run(args)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 883, in run
    elastic_launch(
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 265, in launch_agent
    if result.is_failed():
AttributeError: 'NoneType' object has no attribute 'is_failed'
Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/torchrun", line 10, in <module>
    sys.exit(main())
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in main
    run(args)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 883, in run
    elastic_launch(
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 265, in launch_agent
    if result.is_failed():
AttributeError: 'NoneType' object has no attribute 'is_failed'
Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/torchrun", line 10, in <module>
    sys.exit(main())
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in main
    run(args)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 883, in run
    elastic_launch(
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 265, in launch_agent
    if result.is_failed():
AttributeError: 'NoneType' object has no attribute 'is_failed'
srun: error: lrdn1590: task 13: Exited with exit code 1
srun: error: lrdn1375: tasks 4,6: Exited with exit code 1
srun: error: lrdn1590: tasks 14-15: Exited with exit code 1
srun: error: lrdn1582: tasks 9-11: Exited with exit code 1
srun: error: lrdn0446: tasks 0-3: Exited with exit code 1
Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 169, in <module>
Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 169, in <module>
Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 169, in <module>
Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 169, in <module>
    main_train(
  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 87, in main_train
    main_train(
  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 87, in main_train
Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 169, in <module>
    print(f"[RANK {rank}] Hi! My local rank is {local_rank}, global rank is {rank}, world size is {world_size}")
UnboundLocalError: local variable 'rank' referenced before assignment
    main_train(
  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 87, in main_train
    main_train(
  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 87, in main_train
    print(f"[RANK {rank}] Hi! My local rank is {local_rank}, global rank is {rank}, world size is {world_size}")
UnboundLocalError: local variable 'rank' referenced before assignment
Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 169, in <module>
    main_train(
  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 87, in main_train
Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 169, in <module>
        print(f"[RANK {rank}] Hi! My local rank is {local_rank}, global rank is {rank}, world size is {world_size}")
UnboundLocalError: local variable 'rank' referenced before assignment
    main_train(
  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 87, in main_train
    print(f"[RANK {rank}] Hi! My local rank is {local_rank}, global rank is {rank}, world size is {world_size}")
UnboundLocalError: local variable 'rank' referenced before assignment
print(f"[RANK {rank}] Hi! My local rank is {local_rank}, global rank is {rank}, world size is {world_size}")
UnboundLocalError: local variable 'rank' referenced before assignment
    print(f"[RANK {rank}] Hi! My local rank is {local_rank}, global rank is {rank}, world size is {world_size}")
UnboundLocalError: local variable 'rank' referenced before assignment
    main_train(
  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 87, in main_train
    print(f"[RANK {rank}] Hi! My local rank is {local_rank}, global rank is {rank}, world size is {world_size}")
UnboundLocalError: local variable 'rank' referenced before assignment
Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 169, in <module>
    main_train(
  File "/leonardo/home/userexternal/lpiarull/fddl/autoencoder_ddp/train.py", line 87, in main_train
    print(f"[RANK {rank}] Hi! My local rank is {local_rank}, global rank is {rank}, world size is {world_size}")
UnboundLocalError: local variable 'rank' referenced before assignment
W0615 19:55:25.527000 997611 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 997640 closing signal SIGTERM
W0615 19:55:25.527000 997611 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 997641 closing signal SIGTERM
W0615 19:55:25.528000 997611 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 997643 closing signal SIGTERM
W0615 19:55:25.528000 997611 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 997645 closing signal SIGTERM
W0615 19:55:25.542000 997609 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 997639 closing signal SIGTERM
W0615 19:55:25.542000 997609 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 997642 closing signal SIGTERM
W0615 19:55:25.542000 997609 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 997644 closing signal SIGTERM
W0615 19:55:25.542000 997609 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 997646 closing signal SIGTERM
[W615 19:55:25.044862741 TCPStore.cpp:106] [c10d] sendBytes failed on SocketImpl(fd=3, addr=[lrdn1375-net4-3.leonardo.local]:49550, remote=[lrdn0446-net2-3.leonardo.local]:12355): Broken pipe
Exception raised from sendBytes at /home/conda/feedstock_root/build_artifacts/libtorch_1746251338759/work/torch/csrc/distributed/c10d/Utils.hpp:653 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xae (0x1479711bf5ee in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../.././libc10.so)
frame #1: <unknown function> + 0x6278bfc (0x1479777a5bfc in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../.././libtorch_cpu.so)
frame #2: <unknown function> + 0x627b534 (0x1479777a8534 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../.././libtorch_cpu.so)
frame #3: <unknown function> + 0x627d8a2 (0x1479777aa8a2 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../.././libtorch_cpu.so)
frame #4: c10d::TCPStore::doWait(c10::ArrayRef<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::chrono::duration<long, std::ratio<1l, 1000l> >) + 0x201 (0x1479777ac831 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../.././libtorch_cpu.so)
frame #5: c10d::TCPStore::doGet(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x44 (0x1479777ace54 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../.././libtorch_cpu.so)
frame #6: c10d::TCPStore::get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x12d (0x1479777ae0ad in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../.././libtorch_cpu.so)
frame #7: <unknown function> + 0xc6c0b6 (0x14797f57c0b6 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../../libtorch_python.so)
frame #8: <unknown function> + 0x3ccd58 (0x14797ecdcd58 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../../libtorch_python.so)
frame #9: <unknown function> + 0x13bc66 (0x558a1fbcac66 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #10: _PyObject_MakeTpCall + 0x2d3 (0x558a1fbc4023 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #11: <unknown function> + 0x1478fb (0x558a1fbd68fb in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #12: _PyEval_EvalFrameDefault + 0x2ba5 (0x558a1fbbdc55 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #13: _PyFunction_Vectorcall + 0x6c (0x558a1fbcb0ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #14: _PyEval_EvalFrameDefault + 0x700 (0x558a1fbbb7b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #15: _PyFunction_Vectorcall + 0x6c (0x558a1fbcb0ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #16: _PyEval_EvalFrameDefault + 0x700 (0x558a1fbbb7b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #17: _PyFunction_Vectorcall + 0x6c (0x558a1fbcb0ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #18: _PyEval_EvalFrameDefault + 0x700 (0x558a1fbbb7b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #19: _PyFunction_Vectorcall + 0x6c (0x558a1fbcb0ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #20: _PyEval_EvalFrameDefault + 0x700 (0x558a1fbbb7b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #21: _PyFunction_Vectorcall + 0x6c (0x558a1fbcb0ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #22: _PyEval_EvalFrameDefault + 0x700 (0x558a1fbbb7b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #23: _PyFunction_Vectorcall + 0x6c (0x558a1fbcb0ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #24: _PyEval_EvalFrameDefault + 0x700 (0x558a1fbbb7b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #25: _PyFunction_Vectorcall + 0x6c (0x558a1fbcb0ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #26: _PyEval_EvalFrameDefault + 0x700 (0x558a1fbbb7b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #27: _PyFunction_Vectorcall + 0x6c (0x558a1fbcb0ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #28: _PyEval_EvalFrameDefault + 0x2ba5 (0x558a1fbbdc55 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #29: _PyFunction_Vectorcall + 0x6c (0x558a1fbcb0ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #30: _PyEval_EvalFrameDefault + 0x700 (0x558a1fbbb7b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #31: _PyFunction_Vectorcall + 0x6c (0x558a1fbcb0ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #32: _PyEval_EvalFrameDefault + 0x30c (0x558a1fbbb3bc in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #33: _PyObject_FastCallDictTstate + 0xd0 (0x558a1fbc34b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #34: _PyObject_Call_Prepend + 0x69 (0x558a1fbd4ab9 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #35: <unknown function> + 0x205949 (0x558a1fc94949 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #36: PyObject_Call + 0x20f (0x558a1fbd6f9f in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #37: _PyEval_EvalFrameDefault + 0x2ba5 (0x558a1fbbdc55 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #38: _PyFunction_Vectorcall + 0x6c (0x558a1fbcb0ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #39: _PyEval_EvalFrameDefault + 0x30c (0x558a1fbbb3bc in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #40: _PyFunction_Vectorcall + 0x6c (0x558a1fbcb0ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #41: _PyEval_EvalFrameDefault + 0x2ba5 (0x558a1fbbdc55 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #42: _PyFunction_Vectorcall + 0x6c (0x558a1fbcb0ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #43: _PyEval_EvalFrameDefault + 0x30c (0x558a1fbbb3bc in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #44: <unknown function> + 0x1cc3bc (0x558a1fc5b3bc in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #45: PyEval_EvalCode + 0x87 (0x558a1fc5b307 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #46: <unknown function> + 0x1fc96a (0x558a1fc8b96a in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #47: <unknown function> + 0x1f7df3 (0x558a1fc86df3 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #48: <unknown function> + 0x96f3d (0x558a1fb25f3d in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #49: _PyRun_SimpleFileObject + 0x1bd (0x558a1fc8161d in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #50: _PyRun_AnyFileObject + 0x44 (0x558a1fc811b4 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #51: Py_RunMain + 0x31b (0x558a1fc7e51b in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #52: Py_BytesMain + 0x37 (0x558a1fc4eef7 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #53: __libc_start_main + 0xe5 (0x147980009d85 in /lib64/libc.so.6)
frame #54: <unknown function> + 0x1bfe0e (0x558a1fc4ee0e in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)

W0615 19:55:25.574000 997611 site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py:1292] The node 'lrdn1375.leonardo.local_997611_0' has failed to shutdown the rendezvous '16737543' due to an error of type RendezvousConnectionError.
[W615 19:55:25.053515245 TCPStore.cpp:106] [c10d] sendBytes failed on SocketImpl(fd=3, addr=[lrdn1375-net4-3.leonardo.local]:49550, remote=[lrdn0446-net2-3.leonardo.local]:12355): Broken pipe
Exception raised from sendBytes at /home/conda/feedstock_root/build_artifacts/libtorch_1746251338759/work/torch/csrc/distributed/c10d/Utils.hpp:653 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xae (0x1479711bf5ee in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../.././libc10.so)
frame #1: <unknown function> + 0x6278bfc (0x1479777a5bfc in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../.././libtorch_cpu.so)
frame #2: <unknown function> + 0x627b534 (0x1479777a8534 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../.././libtorch_cpu.so)
frame #3: <unknown function> + 0x627d8a2 (0x1479777aa8a2 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../.././libtorch_cpu.so)
frame #4: c10d::TCPStore::doWait(c10::ArrayRef<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::chrono::duration<long, std::ratio<1l, 1000l> >) + 0x201 (0x1479777ac831 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../.././libtorch_cpu.so)
frame #5: c10d::TCPStore::doGet(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x44 (0x1479777ace54 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../.././libtorch_cpu.so)
frame #6: c10d::TCPStore::get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x12d (0x1479777ae0ad in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../.././libtorch_cpu.so)
frame #7: <unknown function> + 0xc6c0b6 (0x14797f57c0b6 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../../libtorch_python.so)
frame #8: <unknown function> + 0x3ccd58 (0x14797ecdcd58 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../../libtorch_python.so)
frame #9: <unknown function> + 0x13bc66 (0x558a1fbcac66 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #10: _PyObject_MakeTpCall + 0x2d3 (0x558a1fbc4023 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #11: <unknown function> + 0x1478fb (0x558a1fbd68fb in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #12: _PyEval_EvalFrameDefault + 0x2ba5 (0x558a1fbbdc55 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #13: _PyFunction_Vectorcall + 0x6c (0x558a1fbcb0ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #14: _PyEval_EvalFrameDefault + 0x700 (0x558a1fbbb7b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #15: _PyFunction_Vectorcall + 0x6c (0x558a1fbcb0ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #16: _PyEval_EvalFrameDefault + 0x700 (0x558a1fbbb7b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #17: _PyFunction_Vectorcall + 0x6c (0x558a1fbcb0ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #18: _PyEval_EvalFrameDefault + 0x700 (0x558a1fbbb7b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #19: _PyFunction_Vectorcall + 0x6c (0x558a1fbcb0ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #20: _PyEval_EvalFrameDefault + 0x700 (0x558a1fbbb7b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #21: _PyFunction_Vectorcall + 0x6c (0x558a1fbcb0ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #22: _PyEval_EvalFrameDefault + 0x700 (0x558a1fbbb7b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #23: _PyFunction_Vectorcall + 0x6c (0x558a1fbcb0ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #24: _PyEval_EvalFrameDefault + 0x700 (0x558a1fbbb7b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #25: _PyFunction_Vectorcall + 0x6c (0x558a1fbcb0ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #26: _PyEval_EvalFrameDefault + 0x30c (0x558a1fbbb3bc in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #27: _PyObject_FastCallDictTstate + 0xd0 (0x558a1fbc34b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #28: _PyObject_Call_Prepend + 0x69 (0x558a1fbd4ab9 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #29: <unknown function> + 0x205949 (0x558a1fc94949 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #30: PyObject_Call + 0x20f (0x558a1fbd6f9f in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #31: _PyEval_EvalFrameDefault + 0x2ba5 (0x558a1fbbdc55 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #32: _PyFunction_Vectorcall + 0x6c (0x558a1fbcb0ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #33: _PyEval_EvalFrameDefault + 0x30c (0x558a1fbbb3bc in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #34: _PyFunction_Vectorcall + 0x6c (0x558a1fbcb0ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #35: _PyEval_EvalFrameDefault + 0x2ba5 (0x558a1fbbdc55 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #36: _PyFunction_Vectorcall + 0x6c (0x558a1fbcb0ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #37: _PyEval_EvalFrameDefault + 0x30c (0x558a1fbbb3bc in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #38: <unknown function> + 0x1cc3bc (0x558a1fc5b3bc in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #39: PyEval_EvalCode + 0x87 (0x558a1fc5b307 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #40: <unknown function> + 0x1fc96a (0x558a1fc8b96a in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #41: <unknown function> + 0x1f7df3 (0x558a1fc86df3 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #42: <unknown function> + 0x96f3d (0x558a1fb25f3d in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #43: _PyRun_SimpleFileObject + 0x1bd (0x558a1fc8161d in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #44: _PyRun_AnyFileObject + 0x44 (0x558a1fc811b4 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #45: Py_RunMain + 0x31b (0x558a1fc7e51b in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #46: Py_BytesMain + 0x37 (0x558a1fc4eef7 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #47: __libc_start_main + 0xe5 (0x147980009d85 in /lib64/libc.so.6)
frame #48: <unknown function> + 0x1bfe0e (0x558a1fc4ee0e in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)

W0615 19:55:25.580000 997611 site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py:1292] The node 'lrdn1375.leonardo.local_997611_0' has failed to shutdown the rendezvous '16737543' due to an error of type RendezvousConnectionError.
Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 117, in _call_store
    return getattr(self._store, store_op)(*args, **kwargs)
torch.distributed.DistNetworkError: failed to recv, got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/torchrun", line 10, in <module>
    sys.exit(main())
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in main
    run(args)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 883, in run
[W615 19:55:25.055581097 TCPStore.cpp:106] [c10d] sendBytes failed on SocketImpl(fd=3, addr=[lrdn1375.leonardo.local]:49530, remote=[lrdn0446.leonardo.local]:12355): Broken pipe
Exception raised from sendBytes at /home/conda/feedstock_root/build_artifacts/libtorch_1746251338759/work/torch/csrc/distributed/c10d/Utils.hpp:653 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xae (0x147ee9d785ee in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../.././libc10.so)
frame #1: <unknown function> + 0x6278bfc (0x147ef035ebfc in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../.././libtorch_cpu.so)
frame #2: <unknown function> + 0x627b534 (0x147ef0361534 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../.././libtorch_cpu.so)
frame #3: <unknown function> + 0x627d8a2 (0x147ef03638a2 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../.././libtorch_cpu.so)
frame #4: c10d::TCPStore::doWait(c10::ArrayRef<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::chrono::duration<long, std::ratio<1l, 1000l> >) + 0x201 (0x147ef0365831 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../.././libtorch_cpu.so)
frame #5: c10d::TCPStore::doGet(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x44 (0x147ef0365e54 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../.././libtorch_cpu.so)
frame #6: c10d::TCPStore::get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x12d (0x147ef03670ad in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../.././libtorch_cpu.so)
frame #7: <unknown function> + 0xc6c0b6 (0x147ef81350b6 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../../libtorch_python.so)
frame #8: <unknown function> + 0x3ccd58 (0x147ef7895d58 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../../libtorch_python.so)
frame #9: <unknown function> + 0x13bc66 (0x5591cc905c66 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #10: _PyObject_MakeTpCall + 0x2d3 (0x5591cc8ff023 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #11: <unknown function> + 0x1478fb (0x5591cc9118fb in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #12: _PyEval_EvalFrameDefault + 0x2ba5 (0x5591cc8f8c55 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #13: _PyFunction_Vectorcall + 0x6c (0x5591cc9060ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #14: _PyEval_EvalFrameDefault + 0x700 (0x5591cc8f67b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #15: _PyFunction_Vectorcall + 0x6c (0x5591cc9060ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #16: _PyEval_EvalFrameDefault + 0x700 (0x5591cc8f67b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #17: _PyFunction_Vectorcall + 0x6c (0x5591cc9060ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #18: _PyEval_EvalFrameDefault + 0x700 (0x5591cc8f67b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #19: _PyFunction_Vectorcall + 0x6c (0x5591cc9060ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #20: _PyEval_EvalFrameDefault + 0x700 (0x5591cc8f67b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #21: _PyFunction_Vectorcall + 0x6c (0x5591cc9060ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #22: _PyEval_EvalFrameDefault + 0x700 (0x5591cc8f67b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #23: _PyFunction_Vectorcall + 0x6c (0x5591cc9060ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #24: _PyEval_EvalFrameDefault + 0x700 (0x5591cc8f67b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #25: _PyFunction_Vectorcall + 0x6c (0x5591cc9060ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #26: _PyEval_EvalFrameDefault + 0x700 (0x5591cc8f67b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #27: _PyFunction_Vectorcall + 0x6c (0x5591cc9060ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #28: _PyEval_EvalFrameDefault + 0x2ba5 (0x5591cc8f8c55 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #29: _PyFunction_Vectorcall + 0x6c (0x5591cc9060ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #30: _PyEval_EvalFrameDefault + 0x700 (0x5591cc8f67b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #31: _PyFunction_Vectorcall + 0x6c (0x5591cc9060ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #32: _PyEval_EvalFrameDefault + 0x30c (0x5591cc8f63bc in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #33: _PyObject_FastCallDictTstate + 0xd0 (0x5591cc8fe4b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #34: _PyObject_Call_Prepend + 0x69 (0x5591cc90fab9 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #35: <unknown function> + 0x205949 (0x5591cc9cf949 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #36: PyObject_Call + 0x20f (0x5591cc911f9f in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #37: _PyEval_EvalFrameDefault + 0x2ba5 (0x5591cc8f8c55 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #38: _PyFunction_Vectorcall + 0x6c (0x5591cc9060ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #39: _PyEval_EvalFrameDefault + 0x30c (0x5591cc8f63bc in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #40: _PyFunction_Vectorcall + 0x6c (0x5591cc9060ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #41: _PyEval_EvalFrameDefault + 0x2ba5 (0x5591cc8f8c55 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #42: _PyFunction_Vectorcall + 0x6c (0x5591cc9060ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #43: _PyEval_EvalFrameDefault + 0x30c (0x5591cc8f63bc in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #44: <unknown function> + 0x1cc3bc (0x5591cc9963bc in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #45: PyEval_EvalCode + 0x87 (0x5591cc996307 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #46: <unknown function> + 0x1fc96a (0x5591cc9c696a in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #47: <unknown function> + 0x1f7df3 (0x5591cc9c1df3 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #48: <unknown function> + 0x96f3d (0x5591cc860f3d in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #49: _PyRun_SimpleFileObject + 0x1bd (0x5591cc9bc61d in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #50: _PyRun_AnyFileObject + 0x44 (0x5591cc9bc1b4 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #51: Py_RunMain + 0x31b (0x5591cc9b951b in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #52: Py_BytesMain + 0x37 (0x5591cc989ef7 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #53: __libc_start_main + 0xe5 (0x147ef8bc2d85 in /lib64/libc.so.6)
frame #54: <unknown function> + 0x1bfe0e (0x5591cc989e0e in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)

    elastic_launch(
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    result = agent.run()
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/metrics/api.py", line 138, in wrapper
    result = f(*args, **kwargs)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 711, in run
    result = self._invoke_run(role)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 906, in _invoke_run
    num_nodes_waiting = rdzv_handler.num_nodes_waiting()
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 1263, in num_nodes_waiting
W0615 19:55:25.584000 997609 site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py:1292] The node 'lrdn1375-net4-3.leonardo.local_997609_0' has failed to shutdown the rendezvous '16737543' due to an error of type RendezvousConnectionError.
    self._state_holder.sync()
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 437, in sync
    get_response = self._backend.get_state()
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 75, in get_state
    base64_state: bytes = self._call_store("get", self._key)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 119, in _call_store
    raise RendezvousConnectionError(
torch.distributed.elastic.rendezvous.api.RendezvousConnectionError: The connection to the C10d store has failed. See inner exception for details.
[W615 19:55:25.062861965 TCPStore.cpp:106] [c10d] sendBytes failed on SocketImpl(fd=3, addr=[lrdn1375-net4-3.leonardo.local]:49530, remote=[lrdn0446.leonardo.local]:12355): Broken pipe
Exception raised from sendBytes at /home/conda/feedstock_root/build_artifacts/libtorch_1746251338759/work/torch/csrc/distributed/c10d/Utils.hpp:653 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xae (0x147ee9d785ee in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../.././libc10.so)
frame #1: <unknown function> + 0x6278bfc (0x147ef035ebfc in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../.././libtorch_cpu.so)
frame #2: <unknown function> + 0x627b534 (0x147ef0361534 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../.././libtorch_cpu.so)
frame #3: <unknown function> + 0x627d8a2 (0x147ef03638a2 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../.././libtorch_cpu.so)
frame #4: c10d::TCPStore::doWait(c10::ArrayRef<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::chrono::duration<long, std::ratio<1l, 1000l> >) + 0x201 (0x147ef0365831 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../.././libtorch_cpu.so)
frame #5: c10d::TCPStore::doGet(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x44 (0x147ef0365e54 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../.././libtorch_cpu.so)
frame #6: c10d::TCPStore::get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x12d (0x147ef03670ad in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../.././libtorch_cpu.so)
frame #7: <unknown function> + 0xc6c0b6 (0x147ef81350b6 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../../libtorch_python.so)
frame #8: <unknown function> + 0x3ccd58 (0x147ef7895d58 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/../../../libtorch_python.so)
frame #9: <unknown function> + 0x13bc66 (0x5591cc905c66 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #10: _PyObject_MakeTpCall + 0x2d3 (0x5591cc8ff023 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #11: <unknown function> + 0x1478fb (0x5591cc9118fb in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #12: _PyEval_EvalFrameDefault + 0x2ba5 (0x5591cc8f8c55 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #13: _PyFunction_Vectorcall + 0x6c (0x5591cc9060ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #14: _PyEval_EvalFrameDefault + 0x700 (0x5591cc8f67b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #15: _PyFunction_Vectorcall + 0x6c (0x5591cc9060ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #16: _PyEval_EvalFrameDefault + 0x700 (0x5591cc8f67b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #17: _PyFunction_Vectorcall + 0x6c (0x5591cc9060ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #18: _PyEval_EvalFrameDefault + 0x700 (0x5591cc8f67b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #19: _PyFunction_Vectorcall + 0x6c (0x5591cc9060ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #20: _PyEval_EvalFrameDefault + 0x700 (0x5591cc8f67b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #21: _PyFunction_Vectorcall + 0x6c (0x5591cc9060ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #22: _PyEval_EvalFrameDefault + 0x700 (0x5591cc8f67b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #23: _PyFunction_Vectorcall + 0x6c (0x5591cc9060ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #24: _PyEval_EvalFrameDefault + 0x700 (0x5591cc8f67b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #25: _PyFunction_Vectorcall + 0x6c (0x5591cc9060ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #26: _PyEval_EvalFrameDefault + 0x30c (0x5591cc8f63bc in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #27: _PyObject_FastCallDictTstate + 0xd0 (0x5591cc8fe4b0 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #28: _PyObject_Call_Prepend + 0x69 (0x5591cc90fab9 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #29: <unknown function> + 0x205949 (0x5591cc9cf949 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #30: PyObject_Call + 0x20f (0x5591cc911f9f in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #31: _PyEval_EvalFrameDefault + 0x2ba5 (0x5591cc8f8c55 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #32: _PyFunction_Vectorcall + 0x6c (0x5591cc9060ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #33: _PyEval_EvalFrameDefault + 0x30c (0x5591cc8f63bc in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #34: _PyFunction_Vectorcall + 0x6c (0x5591cc9060ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #35: _PyEval_EvalFrameDefault + 0x2ba5 (0x5591cc8f8c55 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #36: _PyFunction_Vectorcall + 0x6c (0x5591cc9060ec in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #37: _PyEval_EvalFrameDefault + 0x30c (0x5591cc8f63bc in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #38: <unknown function> + 0x1cc3bc (0x5591cc9963bc in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #39: PyEval_EvalCode + 0x87 (0x5591cc996307 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #40: <unknown function> + 0x1fc96a (0x5591cc9c696a in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #41: <unknown function> + 0x1f7df3 (0x5591cc9c1df3 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #42: <unknown function> + 0x96f3d (0x5591cc860f3d in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #43: _PyRun_SimpleFileObject + 0x1bd (0x5591cc9bc61d in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #44: _PyRun_AnyFileObject + 0x44 (0x5591cc9bc1b4 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #45: Py_RunMain + 0x31b (0x5591cc9b951b in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #46: Py_BytesMain + 0x37 (0x5591cc989ef7 in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)
frame #47: __libc_start_main + 0xe5 (0x147ef8bc2d85 in /lib64/libc.so.6)
frame #48: <unknown function> + 0x1bfe0e (0x5591cc989e0e in /leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/python)

W0615 19:55:25.590000 997609 site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py:1292] The node 'lrdn1375-net4-3.leonardo.local_997609_0' has failed to shutdown the rendezvous '16737543' due to an error of type RendezvousConnectionError.
Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 117, in _call_store
    return getattr(self._store, store_op)(*args, **kwargs)
torch.distributed.DistNetworkError: failed to recv, got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/bin/torchrun", line 10, in <module>
    sys.exit(main())
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in main
    run(args)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/run.py", line 883, in run
    elastic_launch(
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    result = agent.run()
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/metrics/api.py", line 138, in wrapper
    result = f(*args, **kwargs)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 711, in run
    result = self._invoke_run(role)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 906, in _invoke_run
    num_nodes_waiting = rdzv_handler.num_nodes_waiting()
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 1263, in num_nodes_waiting
    self._state_holder.sync()
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 437, in sync
    get_response = self._backend.get_state()
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 75, in get_state
    base64_state: bytes = self._call_store("get", self._key)
  File "/leonardo/home/userexternal/lpiarull/.conda/envs/fddl_env/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 119, in _call_store
    raise RendezvousConnectionError(
torch.distributed.elastic.rendezvous.api.RendezvousConnectionError: The connection to the C10d store has failed. See inner exception for details.
srun: error: lrdn1375: tasks 5,7: Exited with exit code 1
